import { NextResponse } from "next/server";
import Stripe from "stripe";
import { adminDb } from "@/lib/firebase-admin";
import { db } from "@/lib/firebase";
import { doc, getDoc, setDoc } from "firebase/firestore";
import { generateItineraryData } from "@/app/actions/generateTrip";
import { sendTripEmailAction } from "@/app/actions/sendTripEmail";

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: "2025-01-27.acacia" as any,
});

export async function POST(req: Request) {
  const body = await req.text();
  const signature = req.headers.get("stripe-signature")!;
  
  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(
      body, 
      signature, 
      process.env.STRIPE_WEBHOOK_SECRET!
    );
  } catch (err: any) {
    console.error("Webhook signature verification failed:", err.message);
    return new Response(`Webhook Error: ${err.message}`, { status: 400 });
  }

  // Handle successful checkout completion
  if (event.type === "checkout.session.completed") {
    const session = event.data.object as Stripe.Checkout.Session;
    const meta = session.metadata;
    if (meta) {
      try {
        // Check if the trip was already generated by the redirect success page
        let exists = false;
        if (adminDb) {
          const snap = await adminDb.collection("trips").doc(session.id).get();
          exists = snap.exists;
        } else {
          const tripDocRef = doc(db, "trips", session.id);
          const existingDoc = await getDoc(tripDocRef);
          exists = existingDoc.exists();
        }

        if (exists) {
          console.log("Trip already generated for session:", session.id);
          return NextResponse.json({ received: true });
        }

        const destination = meta.destination || "Destination";
        const days = parseInt(meta.days || "5", 10);
        const budget = meta.budget || "";
        const travelStyle = meta.travelStyle || "";
        let interests: string[] = [];
        try {
          interests = meta.interests ? JSON.parse(meta.interests) : [];
        } catch {
          interests = [];
        }
        const notes = meta.notes || "";
        const startDate = meta.startDate || "";
        const userId = meta.userId || "";

        // 1. Generate the AI travel itinerary data
        const aiResult = await generateItineraryData(destination, days, budget, travelStyle, interests, notes, startDate);

        // 2. Save it directly to Firestore database using session.id as document ID
        const tripPayload = {
          userId,
          destination,
          days,
          budget,
          travelStyle,
          interests,
          aiResult,
          startDate: startDate || null,
          createdAt: new Date().toISOString(),
        };

        if (adminDb) {
          await adminDb.collection("trips").doc(session.id).set(tripPayload);
        } else {
          const tripDocRef = doc(db, "trips", session.id);
          await setDoc(tripDocRef, tripPayload);
        }
        
        const customerEmail = session.customer_details?.email;
        if (customerEmail) {
          sendTripEmailAction(customerEmail, session.id, destination, aiResult).catch((err) => {
            console.error("Failed to send itinerary email in webhook flow:", err);
          });
        }
        
        console.log("Successfully generated trip from Stripe Webhook for session:", session.id);
      } catch (error) {
        console.error("Failed to generate trip inside Stripe Webhook handler:", error);
      }
    }
  }

  return NextResponse.json({ received: true });
}

