"use server";

import nodemailer from "nodemailer";

export async function sendTripEmailAction(
  userEmail: string,
  tripId: string,
  destination: string,
  aiResult: any
) {
  const host = process.env.SMTP_HOST;
  const port = parseInt(process.env.SMTP_PORT || "465", 10);
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;
  const from = process.env.EMAIL_FROM || "Wanderify <no-reply@wanderify.com>";

  if (!host || !user || !pass || user.includes("your-email@gmail.com")) {
    console.warn("SMTP settings are unconfigured or placeholder. Skipping email delivery.");
    return;
  }

  let pdfBuffer: Buffer;
  try {
    // Dynamically import jsPDF on server-side
    const jsPDFModule = await import("jspdf");
    const jsPDF = jsPDFModule.jsPDF || jsPDFModule.default;
    const doc = new jsPDF();

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text(`${destination} Travel Itinerary`, 20, 20);
    
    // Subtitle
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated by Wanderify • Trip ID: ${tripId}`, 20, 28);
    doc.line(20, 32, 190, 32);

    let y = 42;
    
    // Draw daily activities
    aiResult.days.forEach((dayData: any) => {
      // Prevent overflow
      if (y > 265) {
        doc.addPage();
        y = 20;
      }
      
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.text(`Day ${dayData.day}`, 20, y);
      y += 8;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);

      // Morning
      if (dayData.morning && dayData.morning.length > 0) {
        doc.setFont("helvetica", "bold");
        doc.text("Morning:", 20, y);
        doc.setFont("helvetica", "normal");
        const act = dayData.morning[0];
        doc.text(`${act.place} - ${act.description.slice(0, 75)}...`, 40, y);
        y += 6;
      }

      // Afternoon
      if (dayData.afternoon && dayData.afternoon.length > 0) {
        if (y > 275) { doc.addPage(); y = 20; }
        doc.setFont("helvetica", "bold");
        doc.text("Afternoon:", 20, y);
        doc.setFont("helvetica", "normal");
        const act = dayData.afternoon[0];
        doc.text(`${act.place} - ${act.description.slice(0, 75)}...`, 40, y);
        y += 6;
      }

      // Evening
      if (dayData.evening && dayData.evening.length > 0) {
        if (y > 275) { doc.addPage(); y = 20; }
        doc.setFont("helvetica", "bold");
        doc.text("Evening:", 20, y);
        doc.setFont("helvetica", "normal");
        const act = dayData.evening[0];
        doc.text(`${act.place} - ${act.description.slice(0, 75)}...`, 40, y);
        y += 8;
      }
      y += 4;
    });

    const pdfArrayBuffer = doc.output("arraybuffer");
    pdfBuffer = Buffer.from(pdfArrayBuffer);
  } catch (pdfErr) {
    console.error("Failed to generate PDF on server side:", pdfErr);
    throw pdfErr;
  }

  // Configure Nodemailer SMTP transporter
  const transporter = nodemailer.createTransport({
    host,
    port,
    secure: port === 465,
    auth: {
      user,
      pass,
    },
  });

  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "https://wanderify.vercel.app";
  const tripLink = `${baseUrl}/trip/${tripId}`;

  const mailOptions = {
    from,
    to: userEmail,
    subject: `Your Custom Wanderify Itinerary for ${destination}!`,
    html: `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 12px;">
        <h2 style="color: #6366f1; margin-top: 0;">Your trip to ${destination} is ready! ✈️</h2>
        <p>Thank you for using Wanderify. We have generated your fully customized day-by-day travel plan.</p>
        <p><strong>Your itinerary is attached to this email as a PDF file</strong> so you can access it offline during your travels.</p>
        
        <div style="margin: 30px 0; text-align: center;">
          <a href="${tripLink}" style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; font-weight: bold; border-radius: 8px; display: inline-block;">View Itinerary Online</a>
        </div>
        
        <p style="font-size: 12px; color: #888; margin-top: 40px; border-top: 1px solid #eee; padding-top: 15px;">
          This email was sent automatically by Wanderify. If you have any questions, feel free to contact support.
        </p>
      </div>
    `,
    attachments: [
      {
        filename: `${destination.replace(/[^a-zA-Z0-9]/g, "_")}_Itinerary.pdf`,
        content: pdfBuffer,
      },
    ],
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log(`Itinerary confirmation email successfully sent to: ${userEmail}`);
  } catch (emailErr) {
    console.error("Failed to send itinerary confirmation email:", emailErr);
  }
}
