"use server";

import Stripe from "stripe";
import { adminDb } from "@/lib/firebase-admin";
import { generateItineraryData } from "@/app/actions/generateTrip";
import { sendTripEmailAction } from "@/app/actions/sendTripEmail";

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: "2025-01-27.acacia" as any,
});

interface TripConfig {
  destination: string;
  days: string;
  budget: string;
  travelStyle: string;
  travelers: string;
  interests: string[];
  notes: string;
  startDate: string;
  userId: string;
}

export async function createCheckoutSessionAction(config: TripConfig, originUrl: string): Promise<{ url?: string; error?: string }> {
  try {
    if (!process.env.STRIPE_SECRET_KEY) {
      return { error: "STRIPE_SECRET_KEY environment variable is not configured." };
    }

    const session = await stripe.checkout.sessions.create({
      payment_method_types: ["card"],
      line_items: [
        {
          price_data: {
            currency: "usd",
            product_data: {
              name: `AI Trip Planner: ${config.destination}`,
              description: `Complete customized ${config.days}-day travel itinerary.`,
            },
            unit_amount: 199, // $1.99 USD
          },
          quantity: 1,
        },
      ],
      mode: "payment",
      success_url: `${originUrl}/success?session_id={CHECKOUT_SESSION_ID}`,
      cancel_url: `${originUrl}`,
      metadata: {
        userId: config.userId,
        destination: config.destination,
        days: config.days,
        budget: config.budget,
        travelStyle: config.travelStyle,
        travelers: config.travelers,
        interests: JSON.stringify(config.interests),
        notes: config.notes.slice(0, 400), // Truncate notes if they are too long for Stripe metadata limits
        startDate: config.startDate || "",
      },
    });

    return { url: session.url || undefined };
  } catch (error: any) {
    console.error("Failed to create Stripe Checkout session:", error);
    return { error: error.message || "Failed to create Stripe checkout session." };
  }
}

export async function verifyPaymentAndGenerateTripAction(sessionId: string): Promise<{ success: boolean; tripId?: string; error?: string }> {
  try {
    const session = await stripe.checkout.sessions.retrieve(sessionId);

    if (session.payment_status !== "paid") {
      return { success: false, error: "Payment was not completed successfully." };
    }

    const meta = session.metadata;
    if (!meta) {
      return { success: false, error: "No trip metadata found in the session." };
    }

    const destination = meta.destination;
    const days = parseInt(meta.days, 10);
    const budget = meta.budget;
    const travelStyle = meta.travelStyle;
    const travelers = meta.travelers;
    const interests = meta.interests ? (JSON.parse(meta.interests) as string[]) : [];
    const notes = meta.notes || "";
    const startDate = meta.startDate || "";
    const userId = meta.userId;

    // Check if the trip was already generated by the webhook
    const tripDocRef = adminDb.collection("trips").doc(sessionId);
    const existingDoc = await tripDocRef.get();
    if (existingDoc.exists) {
      return { success: true, tripId: sessionId };
    }

    // Generate AI itinerary using the extracted helper
    const aiResult = await generateItineraryData(destination, days, budget, travelStyle, interests, notes, startDate);

    // Save to Firestore using adminDb (Firebase Admin SDK) to bypass client rules
    await tripDocRef.set({
      userId,
      destination,
      days,
      budget,
      travelStyle,
      interests,
      aiResult,
      startDate: startDate || null,
      createdAt: new Date().toISOString(),
    });

    const customerEmail = session.customer_details?.email;
    if (customerEmail) {
      sendTripEmailAction(customerEmail, sessionId, destination, aiResult).catch((err) => {
        console.error("Failed to send itinerary email in redirect flow:", err);
      });
    }

    return { success: true, tripId: sessionId };
  } catch (error: any) {
    console.error("Failed to verify payment and generate trip:", error);
    return { success: false, error: error.message || "Failed to generate your trip itinerary." };
  }
}
