"use server";

import Stripe from "stripe";
import { adminDb } from "@/lib/firebase-admin";
import { db } from "@/lib/firebase";
import { doc, getDoc, setDoc } from "firebase/firestore";
import { generateItineraryData } from "@/app/actions/generateTrip";
import { sendTripEmailAction } from "@/app/actions/sendTripEmail";

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: "2025-01-27.acacia" as any,
});

interface TripConfig {
  destination: string;
  days: string;
  budget: string;
  travelStyle: string;
  travelers: string;
  interests: string[];
  notes: string;
  startDate: string;
  userId: string;
}

export async function createCheckoutSessionAction(config: TripConfig, originUrl: string) {
  try {
    if (!process.env.STRIPE_SECRET_KEY) {
      return { error: "Stripe API key (STRIPE_SECRET_KEY) is missing on the server environment." };
    }

    const session = await stripe.checkout.sessions.create({
      payment_method_types: ["card"],
      line_items: [
        {
          price_data: {
            currency: "usd",
            product_data: {
              name: `AI Trip Planner: ${config.destination}`,
              description: `Complete customized ${config.days}-day travel itinerary.`,
            },
            unit_amount: 199, // $1.99 USD
          },
          quantity: 1,
        },
      ],
      mode: "payment",
      success_url: `${originUrl}/success?session_id={CHECKOUT_SESSION_ID}`,
      cancel_url: `${originUrl}`,
      metadata: {
        userId: config.userId || "",
        destination: config.destination || "",
        days: String(config.days || "5"),
        budget: config.budget || "",
        travelStyle: config.travelStyle || "",
        travelers: config.travelers || "",
        interests: JSON.stringify(config.interests || []),
        notes: (config.notes || "").slice(0, 400),
        startDate: config.startDate || "",
      },
    });

    if (!session.url) {
      return { error: "Stripe session was created but no checkout URL was returned." };
    }

    return { url: session.url };
  } catch (error: any) {
    console.error("Failed to create Stripe Checkout session:", error);
    return { error: error.message || "Failed to create checkout session" };
  }
}

export async function verifyPaymentAndGenerateTripAction(sessionId: string) {
  try {
    if (!sessionId) {
      return { success: false, error: "No checkout session ID provided." };
    }

    const session = await stripe.checkout.sessions.retrieve(sessionId);

    if (session.payment_status !== "paid") {
      return { success: false, error: "Payment was not completed successfully." };
    }

    const meta = session.metadata;
    if (!meta) {
      return { success: false, error: "No trip metadata found in the session." };
    }

    const destination = meta.destination || "Destination";
    const days = parseInt(meta.days || "5", 10);
    const budget = meta.budget || "";
    const travelStyle = meta.travelStyle || "";
    const travelers = meta.travelers || "";
    let interests: string[] = [];
    try {
      interests = meta.interests ? JSON.parse(meta.interests) : [];
    } catch {
      interests = [];
    }
    const notes = meta.notes || "";
    const startDate = meta.startDate || "";
    const userId = meta.userId || "";

    // Check if the trip was already generated by the webhook or prior attempt
    let exists = false;
    if (adminDb) {
      const snap = await adminDb.collection("trips").doc(sessionId).get();
      exists = snap.exists;
    } else {
      const docRef = doc(db, "trips", sessionId);
      const snap = await getDoc(docRef);
      exists = snap.exists();
    }

    if (exists) {
      return { success: true, tripId: sessionId };
    }

    // Generate AI itinerary using Gemini
    const aiResult = await generateItineraryData(destination, days, budget, travelStyle, interests, notes, startDate);

    // Save to Firestore using sessionId as doc ID for idempotency
    const tripPayload = {
      userId,
      destination,
      days,
      budget,
      travelStyle,
      interests,
      aiResult,
      startDate: startDate || null,
      createdAt: new Date().toISOString(),
    };

    if (adminDb) {
      await adminDb.collection("trips").doc(sessionId).set(tripPayload);
    } else {
      const docRef = doc(db, "trips", sessionId);
      await setDoc(docRef, tripPayload);
    }

    const customerEmail = session.customer_details?.email;
    if (customerEmail) {
      sendTripEmailAction(customerEmail, sessionId, destination, aiResult).catch((err) => {
        console.error("Failed to send itinerary email in redirect flow:", err);
      });
    }

    return { success: true, tripId: sessionId };
  } catch (error: any) {
    console.error("Failed to verify payment and generate trip:", error);
    return {
      success: false,
      error: error?.message || "An unexpected error occurred while generating your trip itinerary.",
    };
  }
}

